# Generated by Django 6.0 on 2025-12-11 06:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (e.g., SAVE20, WELCOME50)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount: percentage or fixed amount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateTimeField(help_text='Start date and time when promo code becomes active')),
                ('expire_date', models.DateTimeField(help_text='Expiration date and time for the promo code')),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Maximum number of times this promo code can be used')),
                ('current_usage', models.PositiveIntegerField(default=0, help_text='Current number of times this promo code has been used')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivate', 'Deactivate')], default='active', help_text='Status of the promo code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='frontend_pr_code_d411a9_idx'), models.Index(fields=['status', 'start_date', 'expire_date'], name='frontend_pr_status_78863d_idx')],
            },
        ),
    ]
