# Generated by Django 6.0 on 2025-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the admin', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the admin', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(blank=True, help_text='Password hash (for reference, actual auth uses auth_user table)', max_length=128, null=True),
        ),
    ]
