# Generated by Django 6.0 on 2025-12-22 07:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models, connection, transaction


def create_tables_if_not_exists(apps, schema_editor):
    """Create tables only if they don't exist - handles existing tables gracefully"""
    with connection.cursor() as cursor:
        try:
            # Create frontend_zone if not exists
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS frontend_zone (
                    id BIGSERIAL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL UNIQUE,
                    polygon TEXT NOT NULL,
                    surge_multiplier NUMERIC(5, 2) NOT NULL DEFAULT 1.00 CHECK (surge_multiplier >= 0.01),
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
            
            # Create indexes if not exists
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS frontend_zo_name_06dfab_idx ON frontend_zone (name);")
            except:
                pass
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS frontend_zo_is_acti_cfe859_idx ON frontend_zone (is_active);")
            except:
                pass
            
            # Create zone_driver if not exists
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS zone_driver (
                    id BIGINT PRIMARY KEY,
                    current_location TEXT,
                    status VARCHAR(20) NOT NULL DEFAULT 'offline' CHECK (status IN ('available', 'busy', 'offline')),
                    zone_id BIGINT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
            
            # Add foreign key constraint if zone table exists
            try:
                cursor.execute("""
                    DO $$ 
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint 
                            WHERE conname = 'zone_driver_zone_id_fk'
                        ) THEN
                            ALTER TABLE zone_driver
                            ADD CONSTRAINT zone_driver_zone_id_fk 
                            FOREIGN KEY (zone_id) 
                            REFERENCES frontend_zone(id) 
                            ON DELETE SET NULL;
                        END IF;
                    END $$;
                """)
            except:
                pass
            
            # Create indexes for driver
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS zone_driver_status_idx ON zone_driver (status);")
            except:
                pass
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS zone_driver_zone_id_idx ON zone_driver (zone_id);")
            except:
                pass
            
            # Handle zone_ride table - create if not exists
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS zone_ride (
                    id BIGSERIAL PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    pickup_location TEXT,
                    zone_id BIGINT,
                    fare NUMERIC(10, 2) NOT NULL CHECK (fare >= 0.00),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
            
            # Add missing columns to zone_ride if it already existed
            try:
                cursor.execute("""
                    SELECT column_name
                    FROM information_schema.columns
                    WHERE table_schema = 'public' 
                    AND table_name = 'zone_ride';
                """)
                existing_columns = {row[0] for row in cursor.fetchall()}
                
                if 'pickup_location' not in existing_columns:
                    cursor.execute("ALTER TABLE zone_ride ADD COLUMN IF NOT EXISTS pickup_location TEXT;")
                
                if 'updated_at' not in existing_columns:
                    cursor.execute("ALTER TABLE zone_ride ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;")
                
                if 'zone_id' not in existing_columns:
                    cursor.execute("ALTER TABLE zone_ride ADD COLUMN IF NOT EXISTS zone_id BIGINT;")
            except:
                pass
            
            # Add foreign key constraints
            try:
                cursor.execute("""
                    DO $$ 
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint 
                            WHERE conname = 'zone_ride_user_id_fk'
                        ) THEN
                            ALTER TABLE zone_ride
                            ADD CONSTRAINT zone_ride_user_id_fk 
                            FOREIGN KEY (user_id) 
                            REFERENCES rides_user(id) 
                            ON DELETE CASCADE;
                        END IF;
                    END $$;
                """)
            except:
                pass
            
            try:
                cursor.execute("""
                    DO $$ 
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint 
                            WHERE conname = 'zone_ride_zone_id_fk'
                        ) THEN
                            ALTER TABLE zone_ride
                            ADD CONSTRAINT zone_ride_zone_id_fk 
                            FOREIGN KEY (zone_id) 
                            REFERENCES frontend_zone(id) 
                            ON DELETE SET NULL;
                        END IF;
                    END $$;
                """)
            except:
                pass
            
            # Create indexes for zone_ride
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS zone_ride_user_id_idx ON zone_ride (user_id);")
            except:
                pass
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS zone_ride_zone_id_idx ON zone_ride (zone_id);")
            except:
                pass
            try:
                cursor.execute("CREATE INDEX IF NOT EXISTS zone_ride_created_at_idx ON zone_ride (created_at);")
            except:
                pass
            
        except Exception as e:
            # If table already exists, that's fine - continue
            if "already exists" not in str(e).lower() and "duplicate" not in str(e).lower():
                raise


def reverse_create_tables(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_adminprofile_email_adminprofile_name_and_more'),
    ]

    operations = [
        # Create tables using SQL (handles existing tables)
        migrations.RunPython(
            create_tables_if_not_exists,
            reverse_create_tables,
        ),
        # Register models with Django (without creating tables - they already exist)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Tables already created above
            state_operations=[
                migrations.CreateModel(
                    name='Zone',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text="Name of the zone (e.g., 'Downtown Zone', 'Airport Zone')", max_length=255, unique=True)),
                        ('polygon', models.TextField(help_text="Polygon geometry in WKT format (e.g., 'POLYGON((lon1 lat1, lon2 lat2, lon3 lat3, lon1 lat1))')")),
                        ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Surge pricing multiplier for this zone (e.g., 1.5 for 50% surge)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this zone is currently active')),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the zone was created')),
                    ],
                    options={
                        'verbose_name': 'Zone',
                        'verbose_name_plural': 'Zones',
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['name'], name='frontend_zo_name_06dfab_idx'), models.Index(fields=['is_active'], name='frontend_zo_is_acti_cfe859_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='Driver',
                    fields=[
                        ('id', models.BigIntegerField(help_text='Driver ID', primary_key=True, serialize=False)),
                        ('current_location', models.TextField(blank=True, help_text="Current location as POINT in WKT format (e.g., 'POINT(lon lat)')", null=True)),
                        ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', help_text='Current driver status', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the driver was created')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the driver was last updated')),
                        ('zone', models.ForeignKey(blank=True, help_text='Current zone the driver is in (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='frontend.zone')),
                    ],
                    options={
                        'verbose_name': 'Driver',
                        'verbose_name_plural': 'Drivers',
                        'db_table': 'zone_driver',  # Custom table name
                        'ordering': ['-updated_at'],
                        'indexes': [models.Index(fields=['status'], name='zone_driver_status_idx'), models.Index(fields=['zone'], name='zone_driver_zone_id_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='Ride',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('pickup_location', models.TextField(help_text="Pickup location in WKT format (e.g., 'POINT(lon lat)')")),
                        ('fare', models.DecimalField(decimal_places=2, help_text='Fare amount for the ride', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the ride was created')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the ride was last updated')),
                        ('user', models.ForeignKey(help_text='User who requested the ride', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='frontend.ridesuser')),
                        ('zone', models.ForeignKey(blank=True, help_text='Zone where the ride is taking place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='frontend.zone')),
                    ],
                    options={
                        'verbose_name': 'Ride',
                        'verbose_name_plural': 'Rides',
                        'db_table': 'zone_ride',  # Custom table name
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['user'], name='zone_ride_user_id_idx'), models.Index(fields=['zone'], name='zone_ride_zone_id_idx'), models.Index(fields=['created_at'], name='zone_ride_created_at_idx')],
                    },
                ),
            ],
        ),
    ]
