# Generated by Django 6.0 on 2025-12-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_create_zone_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driver',
            new_name='zone_driver_status_024869_idx',
            old_name='zone_driver_status_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='zone_driver_zone_id_d10d2e_idx',
            old_name='zone_driver_zone_id_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='zone_ride_user_id_7b802b_idx',
            old_name='zone_ride_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='zone_ride_zone_id_ba300f_idx',
            old_name='zone_ride_zone_id_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='zone_ride_created_ed070b_idx',
            old_name='zone_ride_created_at_idx',
        ),
    ]
