# Generated by Django 6.0 on 2025-12-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_update_driver_table_name'),
    ]

    operations = [
        # Column already exists in database, so we only update Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed - column already exists
            state_operations=[
                migrations.AddField(
                    model_name='ride',
                    name='vehicle_type',
                    field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('auto', 'Auto'), ('5seater', '5 Seater'), ('7seater', '7 Seater')], default='car', help_text='Type of vehicle for the ride', max_length=50),
                ),
            ],
        ),
    ]
