# Generated by Django 6.0 on 2025-12-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_ride_vehicle_type'),
    ]

    operations = [
        # Column already exists in database, so we only update Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed - column already exists
            state_operations=[
                migrations.AddField(
                    model_name='ride',
                    name='status',
                    field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the ride', max_length=20),
                ),
            ],
        ),
    ]
