# Generated by Django 6.0 on 2025-12-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.CharField(blank=True, help_text='City name where this zone is located', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['city'], name='frontend_zo_city_0cfca8_idx'),
        ),
    ]
