# Generated by Django 6.0 on 2025-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_add_city_to_zone'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to rename the field in model state only
        # This keeps the database column as 'id' but changes the model field name to 'zone_id'
        migrations.SeparateDatabaseAndState(
            # Database state: no changes (column stays as 'id')
            database_operations=[],
            # Model state: rename field from 'id' to 'zone_id'
            state_operations=[
                migrations.RenameField(
                    model_name='zone',
                    old_name='id',
                    new_name='zone_id',
                ),
                # Update the field definition to explicitly set db_column='id'
                migrations.AlterField(
                    model_name='zone',
                    name='zone_id',
                    field=models.AutoField(db_column='id', help_text='Zone ID (primary key)', primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
