# Generated by Django 6.0 on 2025-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_update_zone_model_add_zone_id'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to revert field name from 'zone_id' to 'id'
        # This keeps the database column as 'id' (no database changes needed)
        migrations.SeparateDatabaseAndState(
            # Database state: no changes (column stays as 'id')
            database_operations=[],
            # Model state: rename field from 'zone_id' back to 'id'
            state_operations=[
                migrations.RenameField(
                    model_name='zone',
                    old_name='zone_id',
                    new_name='id',
                ),
            ],
        ),
    ]
