# Generated by Django 6.0 on 2025-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_zone_id'),
    ]

    operations = [
        # Step 1: Rename the database column from 'id' to 'zone_id'
        # This must be done before updating the model field
        migrations.RunSQL(
            # Rename the column in the database
            sql="ALTER TABLE frontend_zone RENAME COLUMN id TO zone_id;",
            # Reverse operation: rename back to id
            reverse_sql="ALTER TABLE frontend_zone RENAME COLUMN zone_id TO id;",
        ),
        # Step 2: Update foreign key constraints to reference the new column name
        migrations.RunSQL(
            # Drop old foreign key constraints
            sql="""
                DO $$
                BEGIN
                    -- Drop zone_driver foreign key if it exists
                    IF EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'zone_driver_zone_id_fk'
                    ) THEN
                        ALTER TABLE zone_driver DROP CONSTRAINT zone_driver_zone_id_fk;
                    END IF;
                    
                    -- Drop zone_ride foreign key if it exists
                    IF EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'zone_ride_zone_id_fk'
                    ) THEN
                        ALTER TABLE zone_ride DROP CONSTRAINT zone_ride_zone_id_fk;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                -- Reverse: constraints will be recreated by Django
                SELECT 1;
            """,
        ),
        # Step 3: Recreate foreign key constraints with new column name
        migrations.RunSQL(
            sql="""
                -- Recreate zone_driver foreign key
                ALTER TABLE zone_driver 
                ADD CONSTRAINT zone_driver_zone_id_fk 
                FOREIGN KEY (zone_id) 
                REFERENCES frontend_zone(zone_id) 
                ON DELETE SET NULL;
                
                -- Recreate zone_ride foreign key
                ALTER TABLE zone_ride 
                ADD CONSTRAINT zone_ride_zone_id_fk 
                FOREIGN KEY (zone_id) 
                REFERENCES frontend_zone(zone_id) 
                ON DELETE SET NULL;
            """,
            reverse_sql="""
                -- Drop the constraints (will be recreated by reverse of step 2)
                ALTER TABLE zone_driver DROP CONSTRAINT IF EXISTS zone_driver_zone_id_fk;
                ALTER TABLE zone_ride DROP CONSTRAINT IF EXISTS zone_ride_zone_id_fk;
            """,
        ),
        # Step 4: Update the model field definition
        migrations.SeparateDatabaseAndState(
            # Database state: already renamed above
            database_operations=[],
            # Model state: update field definition
            state_operations=[
                migrations.RemoveField(
                    model_name='zone',
                    name='id',
                ),
                migrations.AddField(
                    model_name='zone',
                    name='zone_id',
                    field=models.AutoField(db_column='zone_id', help_text='Zone ID (primary key)', primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
