# Generated by Django 6.0 on 2025-12-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_rename_zone_id_column'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle database and model state separately
        migrations.SeparateDatabaseAndState(
            # Database operations: Drop tables if they exist
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- Drop foreign key constraints first (only if tables exist)
                        DO $$
                        BEGIN
                            -- Drop zone_driver foreign key if table and constraint exist
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'zone_driver') THEN
                                IF EXISTS (
                                    SELECT 1 FROM pg_constraint 
                                    WHERE conname = 'zone_driver_zone_id_fk'
                                ) THEN
                                    ALTER TABLE zone_driver DROP CONSTRAINT zone_driver_zone_id_fk;
                                END IF;
                            END IF;
                            
                            -- Drop zone_ride foreign keys if table exists
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'zone_ride') THEN
                                IF EXISTS (
                                    SELECT 1 FROM pg_constraint 
                                    WHERE conname = 'zone_ride_zone_id_fk'
                                ) THEN
                                    ALTER TABLE zone_ride DROP CONSTRAINT zone_ride_zone_id_fk;
                                END IF;
                                
                                IF EXISTS (
                                    SELECT 1 FROM pg_constraint 
                                    WHERE conname = 'zone_ride_user_id_fk'
                                ) THEN
                                    ALTER TABLE zone_ride DROP CONSTRAINT zone_ride_user_id_fk;
                                END IF;
                            END IF;
                        END $$;
                        
                        -- Drop indexes (IF EXISTS handles non-existent indexes)
                        DROP INDEX IF EXISTS zone_driver_status_idx;
                        DROP INDEX IF EXISTS zone_driver_zone_id_idx;
                        DROP INDEX IF EXISTS zone_ride_user_id_idx;
                        DROP INDEX IF EXISTS zone_ride_zone_id_idx;
                        DROP INDEX IF EXISTS zone_ride_created_at_idx;
                        
                        -- Drop tables (IF EXISTS handles non-existent tables)
                        DROP TABLE IF EXISTS zone_driver CASCADE;
                        DROP TABLE IF EXISTS zone_ride CASCADE;
                    """,
                    reverse_sql="""
                        -- Reverse migration: Recreate tables (if needed for rollback)
                        -- Note: This is a simplified recreation - actual structure may vary
                        -- In practice, you would need to restore from backup for a proper rollback
                        SELECT 1;
                    """,
                ),
            ],
            # Model state: Remove models from Django's state
            state_operations=[
                migrations.DeleteModel(
                    name='Driver',
                ),
                migrations.DeleteModel(
                    name='Ride',
                ),
            ],
        ),
    ]

