# Generated by Django 6.0 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_delete_zone_driver_and_zone_ride'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Alter table structure
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- Rename 'name' column to 'zone_name' if it exists
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'name'
                            ) THEN
                                ALTER TABLE frontend_zone RENAME COLUMN name TO zone_name;
                            END IF;
                        END $$;
                        
                        -- Add 'country' column if it doesn't exist
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'country'
                            ) THEN
                                ALTER TABLE frontend_zone ADD COLUMN country VARCHAR(255);
                            END IF;
                        END $$;
                        
                        -- Add 'state' column if it doesn't exist
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'state'
                            ) THEN
                                ALTER TABLE frontend_zone ADD COLUMN state VARCHAR(255);
                            END IF;
                        END $$;
                        
                        -- Add 'priority' column if it doesn't exist
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'priority'
                            ) THEN
                                ALTER TABLE frontend_zone ADD COLUMN priority INTEGER DEFAULT 0;
                            END IF;
                        END $$;
                        
                        -- Add 'updated_at' column if it doesn't exist
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'updated_at'
                            ) THEN
                                ALTER TABLE frontend_zone ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
                            END IF;
                        END $$;
                        
                        -- Convert is_active boolean to status VARCHAR
                        DO $$
                        BEGIN
                            -- Add status column if it doesn't exist
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'status'
                            ) THEN
                                ALTER TABLE frontend_zone ADD COLUMN status VARCHAR(20) DEFAULT 'Active';
                                
                                -- Migrate data from is_active to status
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.columns 
                                    WHERE table_name = 'frontend_zone' AND column_name = 'is_active'
                                ) THEN
                                    UPDATE frontend_zone 
                                    SET status = CASE 
                                        WHEN is_active = TRUE THEN 'Active' 
                                        ELSE 'Inactive' 
                                    END;
                                END IF;
                            END IF;
                        END $$;
                        
                        -- Drop old columns if they exist
                        DO $$
                        BEGIN
                            -- Drop polygon column if it exists
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'polygon'
                            ) THEN
                                ALTER TABLE frontend_zone DROP COLUMN polygon;
                            END IF;
                            
                            -- Drop surge_multiplier column if it exists
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'surge_multiplier'
                            ) THEN
                                ALTER TABLE frontend_zone DROP COLUMN surge_multiplier;
                            END IF;
                            
                            -- Drop is_active column if it exists (after migration to status)
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' AND column_name = 'is_active'
                            ) THEN
                                ALTER TABLE frontend_zone DROP COLUMN is_active;
                            END IF;
                        END $$;
                        
                        -- Update indexes
                        DROP INDEX IF EXISTS frontend_zo_name_06dfab_idx;
                        DROP INDEX IF EXISTS frontend_zo_is_acti_cfe859_idx;
                        
                        -- Create new indexes
                        CREATE INDEX IF NOT EXISTS frontend_zone_zone_name_idx ON frontend_zone (zone_name);
                        CREATE INDEX IF NOT EXISTS frontend_zone_country_idx ON frontend_zone (country);
                        CREATE INDEX IF NOT EXISTS frontend_zone_state_idx ON frontend_zone (state);
                        CREATE INDEX IF NOT EXISTS frontend_zone_city_idx ON frontend_zone (city);
                        CREATE INDEX IF NOT EXISTS frontend_zone_status_idx ON frontend_zone (status);
                        CREATE INDEX IF NOT EXISTS frontend_zone_priority_idx ON frontend_zone (priority);
                    """,
                    reverse_sql="""
                        -- Reverse migration (simplified - would need to restore data from backup for full rollback)
                        SELECT 1;
                    """,
                ),
            ],
            # Model state: Update model fields
            state_operations=[
                # Remove old fields
                migrations.RemoveField(
                    model_name='zone',
                    name='name',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='polygon',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='surge_multiplier',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='is_active',
                ),
                # Add new fields
                migrations.AddField(
                    model_name='zone',
                    name='zone_name',
                    field=models.CharField(help_text="Name of the zone (e.g., 'Downtown Zone', 'Airport Zone')", max_length=255, unique=True),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='zone',
                    name='country',
                    field=models.CharField(blank=True, help_text='Country where this zone is located', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='zone',
                    name='state',
                    field=models.CharField(blank=True, help_text='State/Province where this zone is located', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='zone',
                    name='priority',
                    field=models.IntegerField(default=0, help_text='Priority of the zone (higher number = higher priority)'),
                ),
                migrations.AddField(
                    model_name='zone',
                    name='status',
                    field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text="Status of the zone: Active or Inactive", max_length=20),
                ),
                migrations.AddField(
                    model_name='zone',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, help_text='Timestamp when the zone was last updated'),
                ),
            ],
        ),
    ]

