# Generated by Django 6.0 on 2025-12-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_update_zone_table_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.RemoveIndex(
            model_name='zone',
            name='frontend_zo_name_06dfab_idx',
        ),
        migrations.RemoveIndex(
            model_name='zone',
            name='frontend_zo_is_acti_cfe859_idx',
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['zone_name'], name='frontend_zo_zone_na_9587ee_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['country'], name='frontend_zo_country_a3b811_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['state'], name='frontend_zo_state_a6a8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['status'], name='frontend_zo_status_544706_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['priority'], name='frontend_zo_priorit_4ed28f_idx'),
        ),
    ]
