# Generated by Django 6.0 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Convert VARCHAR status to BOOLEAN
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- Convert status column from VARCHAR to BOOLEAN
                        DO $$
                        BEGIN
                            -- Check if status column exists and is VARCHAR
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' 
                                AND column_name = 'status'
                                AND data_type = 'character varying'
                            ) THEN
                                -- Add temporary boolean column
                                ALTER TABLE frontend_zone ADD COLUMN status_new BOOLEAN DEFAULT TRUE;
                                
                                -- Migrate data: Convert string values to boolean
                                UPDATE frontend_zone 
                                SET status_new = CASE 
                                    WHEN LOWER(status) IN ('active', 'true', '1', 'yes') THEN TRUE
                                    WHEN LOWER(status) IN ('inactive', 'false', '0', 'no') THEN FALSE
                                    ELSE TRUE  -- Default to TRUE if value is unexpected
                                END;
                                
                                -- Drop old status column
                                ALTER TABLE frontend_zone DROP COLUMN status;
                                
                                -- Rename new column to status
                                ALTER TABLE frontend_zone RENAME COLUMN status_new TO status;
                                
                                -- Set NOT NULL constraint
                                ALTER TABLE frontend_zone ALTER COLUMN status SET NOT NULL;
                                ALTER TABLE frontend_zone ALTER COLUMN status SET DEFAULT TRUE;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        -- Reverse: Convert BOOLEAN back to VARCHAR
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_zone' 
                                AND column_name = 'status'
                                AND data_type = 'boolean'
                            ) THEN
                                -- Add temporary VARCHAR column
                                ALTER TABLE frontend_zone ADD COLUMN status_old VARCHAR(20) DEFAULT 'Active';
                                
                                -- Migrate data: Convert boolean to string
                                UPDATE frontend_zone 
                                SET status_old = CASE 
                                    WHEN status = TRUE THEN 'Active'
                                    WHEN status = FALSE THEN 'Inactive'
                                    ELSE 'Active'
                                END;
                                
                                -- Drop boolean column
                                ALTER TABLE frontend_zone DROP COLUMN status;
                                
                                -- Rename VARCHAR column to status
                                ALTER TABLE frontend_zone RENAME COLUMN status_old TO status;
                            END IF;
                        END $$;
                    """,
                ),
            ],
            # Model state: Update field type to BooleanField
            state_operations=[
                migrations.AlterField(
                    model_name='zone',
                    name='status',
                    field=models.BooleanField(default=True, help_text='Status of the zone: True for active, False for inactive'),
                ),
            ],
        ),
    ]

