# Generated by Django 6.0 on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_country_state_city_state_state_country_7cf25f_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Drop old tables and create new state table
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- Drop old tables if they exist
                        DROP TABLE IF EXISTS city CASCADE;
                        DROP TABLE IF EXISTS state CASCADE;
                        DROP TABLE IF EXISTS country CASCADE;
                        
                        -- Create new state table with country, state_name, city
                        CREATE TABLE IF NOT EXISTS state (
                            id BIGSERIAL PRIMARY KEY,
                            country VARCHAR(255) NOT NULL,
                            state_name VARCHAR(255) NOT NULL,
                            city VARCHAR(255) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT state_country_state_city_unique UNIQUE (country, state_name, city)
                        );
                        
                        -- Create indexes
                        CREATE INDEX IF NOT EXISTS state_country_idx ON state (country);
                        CREATE INDEX IF NOT EXISTS state_state_name_idx ON state (state_name);
                        CREATE INDEX IF NOT EXISTS state_city_idx ON state (city);
                        CREATE INDEX IF NOT EXISTS state_country_state_name_idx ON state (country, state_name);
                    """,
                    reverse_sql="""
                        -- Reverse: Recreate old tables (simplified - would need data restoration for full rollback)
                        DROP TABLE IF EXISTS state CASCADE;
                        CREATE TABLE IF NOT EXISTS country (
                            id BIGSERIAL PRIMARY KEY,
                            name VARCHAR(255) UNIQUE NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                        );
                        CREATE TABLE IF NOT EXISTS state (
                            id BIGSERIAL PRIMARY KEY,
                            country_id BIGINT NOT NULL,
                            name VARCHAR(255) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
                            UNIQUE (country_id, name)
                        );
                        CREATE TABLE IF NOT EXISTS city (
                            id BIGSERIAL PRIMARY KEY,
                            state_id BIGINT NOT NULL,
                            name VARCHAR(255) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE CASCADE,
                            UNIQUE (state_id, name)
                        );
                    """,
                ),
            ],
            # Model state: Remove old models, recreate State model
            state_operations=[
                migrations.DeleteModel(
                    name='City',
                ),
                migrations.DeleteModel(
                    name='Country',
                ),
                migrations.DeleteModel(
                    name='State',
                ),
                migrations.CreateModel(
                    name='State',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('country', models.CharField(help_text='Country name', max_length=255)),
                        ('state_name', models.CharField(help_text='State name', max_length=255)),
                        ('city', models.CharField(help_text='City name', max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'State',
                        'verbose_name_plural': 'States',
                        'db_table': 'state',
                        'ordering': ['country', 'state_name', 'city'],
                        'unique_together': {('country', 'state_name', 'city')},
                    },
                ),
                migrations.AddIndex(
                    model_name='state',
                    index=models.Index(fields=['country'], name='state_country_c8261c_idx'),
                ),
                migrations.AddIndex(
                    model_name='state',
                    index=models.Index(fields=['state_name'], name='state_state_n_9abc1f_idx'),
                ),
                migrations.AddIndex(
                    model_name='state',
                    index=models.Index(fields=['city'], name='state_city_9f9d5d_idx'),
                ),
                migrations.AddIndex(
                    model_name='state',
                    index=models.Index(fields=['country', 'state_name'], name='state_country_0d3184_idx'),
                ),
            ],
        ),
    ]

