# Generated by Django 6.0 on 2025-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_convert_to_single_state_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-priority', 'country', 'state_name', 'city'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='state',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority of the zone (higher number = higher priority)'),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.BooleanField(default=True, help_text='Status: True for active, False for inactive'),
        ),
        migrations.AddField(
            model_name='state',
            name='zone_name',
            field=models.CharField(blank=True, help_text='Zone name', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['zone_name'], name='state_zone_na_22f892_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['priority'], name='state_priorit_7c2232_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['status'], name='state_status_524fbb_idx'),
        ),
    ]
