# Generated by Django 6.0 on 2025-12-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_alter_state_options_state_priority_state_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Drop the state table
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        # Drop indexes first
                        "DROP INDEX IF EXISTS state_country_c8261c_idx;",
                        "DROP INDEX IF EXISTS state_state_n_9abc1f_idx;",
                        "DROP INDEX IF EXISTS state_city_9f9d5d_idx;",
                        "DROP INDEX IF EXISTS state_country_0d3184_idx;",
                        "DROP INDEX IF EXISTS state_zone_na_22f892_idx;",
                        "DROP INDEX IF EXISTS state_priorit_7c2232_idx;",
                        "DROP INDEX IF EXISTS state_status_524fbb_idx;",
                        # Drop unique constraint if exists
                        "ALTER TABLE state DROP CONSTRAINT IF EXISTS state_country_state_city_unique;",
                        # Drop the table
                        "DROP TABLE IF EXISTS state CASCADE;",
                    ],
                    reverse_sql=[
                        # Reverse operation is not applicable for deletion
                    ],
                ),
            ],
            # Model state: Remove State model from Django's state
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='state',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_country_c8261c_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_state_n_9abc1f_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_city_9f9d5d_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_country_0d3184_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_zone_na_22f892_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_priorit_7c2232_idx',
                ),
                migrations.RemoveIndex(
                    model_name='state',
                    name='state_status_524fbb_idx',
                ),
                migrations.DeleteModel(
                    name='State',
                ),
            ],
        ),
    ]
