# Generated by Django 6.0 on 2025-12-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_delete_state_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(help_text='Role ID (primary key)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the role (e.g., 'Admin', 'Manager', 'User')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its permissions', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='role_name_796487_idx'), models.Index(fields=['is_active'], name='role_is_acti_d578e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='User ID (primary key)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the user (must be unique)', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the user', max_length=20, null=True)),
                ('password', models.CharField(help_text='Hashed password (stored securely)', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user was last updated')),
                ('role_id', models.ForeignKey(blank=True, db_column='role_id', help_text='Foreign key to Role table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='frontend.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_email_7bbb4c_idx'), models.Index(fields=['role_id'], name='user_role_id_9c10d6_idx'), models.Index(fields=['is_active'], name='user_is_acti_7f3bc2_idx'), models.Index(fields=['created_at'], name='user_created_855a50_idx')],
            },
        ),
    ]
