# Generated by Django 6.0 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_role_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='role',
            name='role_name_796487_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='role_is_acti_d578e4_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(blank=True, help_text='Role ID for RBAC', null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
