# Generated by Django 6.0 on 2025-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_remove_role_role_name_796487_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='frontend_us_email_88ecbd_idx',
            old_name='user_email_7bbb4c_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='frontend_us_role_id_7c4acd_idx',
            old_name='user_role_id_9c10d6_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='frontend_us_is_acti_6d7465_idx',
            old_name='user_is_acti_7f3bc2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='frontend_us_created_43718a_idx',
            old_name='user_created_855a50_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, help_text='Confirm password (stored securely)', max_length=128, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='frontend_user',
        ),
    ]
