# Generated by Django 6.0 on 2025-12-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_rename_user_email_7bbb4c_idx_frontend_us_email_88ecbd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', help_text='Role ID (primary key)', primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text="Name of the role (e.g., 'Admin', 'Manager', 'User')", max_length=255, unique=True)),
                ('page_permission', models.CharField(blank=True, help_text='Page or module name for this permission set', max_length=255, null=True)),
                ('view', models.BooleanField(default=False, help_text='Permission to view/view data')),
                ('edit', models.BooleanField(default=False, help_text='Permission to edit/update data')),
                ('delete', models.BooleanField(default=False, help_text='Permission to delete data')),
                ('create', models.BooleanField(default=False, help_text='Permission to create new data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active (True) or inactive (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the role was created')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'frontend_role',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role_name'], name='frontend_ro_role_na_7b1621_idx'), models.Index(fields=['page_permission'], name='frontend_ro_page_pe_181fa8_idx'), models.Index(fields=['is_active'], name='frontend_ro_is_acti_4f1fdb_idx'), models.Index(fields=['created_at'], name='frontend_ro_created_ddc2cb_idx')],
            },
        ),
    ]
