# Generated by Django 6.0 on 2025-12-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='activate', help_text='Role status: activate or deactivate', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='activate', help_text='User status: activate or deactivate', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this role is active (synced with status)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user account is active (synced with status)'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['status'], name='frontend_ro_status_8692db_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='frontend_us_status_660cc1_idx'),
        ),
    ]
