# Generated by Django 6.0 on 2025-12-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_role_status_user_status_alter_role_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='role',
            name='frontend_ro_status_8692db_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='frontend_us_status_660cc1_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this role is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user account is active'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
