# Generated by Django 6.0 on 2026-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_remove_role_frontend_ro_status_8692db_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='role',
            name='frontend_ro_role_na_7b1621_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='frontend_ro_page_pe_181fa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='frontend_ro_is_acti_4f1fdb_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='frontend_ro_created_ddc2cb_idx',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
