# Generated by Django 6.0 on 2026-01-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_remove_role_frontend_ro_role_na_7b1621_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(db_column='role_id', help_text='Role identifier (e.g., R001, R002)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role name (e.g., Super Admin, Admin)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('default_page', models.CharField(default='/', help_text='Default page path after login', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'frontend_role',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='idx_roles_name'), models.Index(fields=['is_active'], name='idx_roles_active')],
            },
        ),
    ]
