# Generated by Django 6.0 on 2026-01-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='page_permission',
            field=models.CharField(blank=True, help_text='Page or module name for this permission set', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['page_permission'], name='idx_roles_page_permission'),
        ),
    ]
