# Generated by Django 6.0 on 2026-01-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_role_page_permission_role_idx_roles_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('page_path', models.CharField(help_text="Page route path (e.g., '/', '/users')", max_length=255)),
                ('permission_type', models.CharField(help_text='Permission type (view, create, edit, delete, etc.)', max_length=50)),
                ('is_allowed', models.BooleanField(default=True, help_text='Whether permission is allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('role', models.ForeignKey(db_column='role_id', help_text='Role identifier (foreign key to frontend_role)', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='frontend.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'frontend_role_permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'page_path'], name='idx_role_perms_role_page'), models.Index(fields=['page_path', 'permission_type'], name='idx_role_perms_page_perm')],
                'unique_together': {('role', 'page_path', 'permission_type')},
            },
        ),
    ]
