# Generated by Django 6.0 on 2026-01-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Assignment timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether assignment is active')),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', help_text='User who assigned the role (foreign key to auth_user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to='frontend.user')),
                ('role', models.ForeignKey(db_column='role_id', help_text='Role identifier (foreign key to frontend_role)', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='frontend.role')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User ID (foreign key to auth_user)', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='frontend.user')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'frontend_user_roles',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_user_roles_user'), models.Index(fields=['role', 'is_active'], name='idx_user_roles_role')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
