# Generated by Django 6.0 on 2026-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='role_name',
            field=models.CharField(blank=True, help_text='Role name (denormalized from role table for easier querying)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role_name'], name='idx_role_perms_role_name'),
        ),
    ]
