# Generated by Django 6.0 on 2026-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_rolepermission_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='idx_role_perms_role_name',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='role_name',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['name'], name='idx_role_perms_name'),
        ),
    ]
