# Generated by Django 6.0 on 2026-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_remove_rolepermission_idx_role_perms_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
