# Generated by Django 6.0 on 2026-01-05
#
# IMPORTANT: This migration requires ALTER privileges on frontend_role_permissions table
# If you get a permission error, see README_REMOVE_ID_COLUMN.md for instructions

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_alter_rolepermission_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Remove id column and set composite primary key
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        -- NOTE: This migration requires ALTER privileges on frontend_role_permissions table
                        -- If you get a permission error, run manual_sql_remove_id_column.sql first, 
                        -- then fake this migration: python manage.py migrate frontend 0039 --fake
                        
                        -- Step 1: Drop the existing primary key constraint if it exists
                        DO $$
                        BEGIN
                            -- Drop the existing primary key constraint if it exists
                            IF EXISTS (
                                SELECT 1 FROM pg_constraint 
                                WHERE conname = 'frontend_role_permissions_pkey'
                            ) THEN
                                ALTER TABLE frontend_role_permissions DROP CONSTRAINT frontend_role_permissions_pkey;
                            END IF;
                            
                            -- Step 2: Drop the id column if it exists
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'frontend_role_permissions' 
                                AND column_name = 'id'
                            ) THEN
                                ALTER TABLE frontend_role_permissions DROP COLUMN id;
                            END IF;
                            
                            -- Step 3: Create composite primary key on (role_id, page_path, permission_type)
                            -- Only if it doesn't already exist
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_constraint 
                                WHERE conname = 'frontend_role_permissions_pkey'
                            ) THEN
                                ALTER TABLE frontend_role_permissions 
                                ADD PRIMARY KEY (role_id, page_path, permission_type);
                            END IF;
                        EXCEPTION
                            WHEN insufficient_privilege THEN
                                RAISE EXCEPTION 'Insufficient privileges: Please run manual_sql_remove_id_column.sql as a superuser or table owner, then fake this migration with: python manage.py migrate frontend 0039 --fake';
                        END $$;
                    """,
                    reverse_sql="""
                        -- Reverse: Add back id column and set it as primary key
                        ALTER TABLE frontend_role_permissions DROP CONSTRAINT IF EXISTS frontend_role_permissions_pkey;
                        
                        ALTER TABLE frontend_role_permissions 
                        ADD COLUMN id BIGSERIAL PRIMARY KEY;
                    """,
                ),
            ],
            # Model state: Remove id field from Django's model state
            state_operations=[
                migrations.RemoveField(
                    model_name='rolepermission',
                    name='id',
                ),
            ],
        ),
    ]
