# Generated by Django 6.0 on 2026-01-05
#
# This migration adds the 'id' field to Django's model state but does NOT create it in the database.
# The database uses a composite primary key (role_id, page_path, permission_type) instead.
# This is a workaround because Django requires a primary key field in models.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_remove_rolepermission_id_column'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Do nothing - the database already has composite PK
            database_operations=[],
            # Model state: Add 'id' field for Django ORM compatibility (but it won't exist in DB)
            state_operations=[
                migrations.AddField(
                    model_name='rolepermission',
                    name='id',
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                        help_text="Django ORM primary key (not in database - database uses composite PK)"
                    ),
                ),
            ],
        ),
    ]

