# Generated by Django 6.0 on 2026-01-05
#
# IMPORTANT: This migration requires the database column to be deleted manually first!
# Run this SQL in pgAdmin before running this migration:
#   ALTER TABLE frontend_role_permissions DROP CONSTRAINT IF EXISTS frontend_role_permissions_pkey;
#   ALTER TABLE frontend_role_permissions DROP COLUMN IF EXISTS id;
#   ALTER TABLE frontend_role_permissions ADD PRIMARY KEY (role_id, page_path, permission_type);
# Then fake this migration: python manage.py migrate frontend 0042 --fake

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_prevent_id_field_creation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Do nothing - column should be deleted manually
            database_operations=[],
            # Model state: Remove id/permission_id field completely
            state_operations=[
                migrations.RemoveField(
                    model_name='rolepermission',
                    name='id',
                ),
            ],
        ),
    ]
