# Generated by Django 6.0 on 2026-01-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_remove_rolepermission_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
    ]
