# Generated by Django 6.0 on 2026-01-05 06:20
#
# IMPORTANT: This migration adds 'id' field to Django's model state only.
# The 'id' column does NOT exist in the database - database uses composite PK.
# This is a workaround because Django requires a primary key field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_alter_rolepermission_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Do nothing - id column doesn't exist in database
            database_operations=[],
            # Model state: Add id field for Django ORM compatibility
            state_operations=[
                migrations.AddField(
                    model_name='rolepermission',
                    name='id',
                    field=models.BigAutoField(
                        help_text='Django ORM primary key (not in database - database uses composite PK)', 
                        primary_key=True, 
                        serialize=False
                    ),
                ),
            ],
        ),
    ]
