# Generated by Django 6.0 on 2026-01-09 06:24
# Modified to handle permission issues - requires manual SQL execution

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_rolepermission_id'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to separate Django state from database changes
        # Database changes must be done manually via SQL script (see manual_sql_alter_role_id.sql)
        migrations.SeparateDatabaseAndState(
            # Database operations: Empty - will be done manually by DBA
            database_operations=[],
            # State operations: Update Django's model state
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='role_id',
                    field=models.CharField(blank=True, help_text="Role ID for RBAC (supports both string like 'R001' and integer values)", max_length=50, null=True),
                ),
            ],
        ),
    ]
