#version: "3.9"
services:
  backend:
    build: ./backend
    container_name: django_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    #depends_on:
    #  - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  #db:
  #  image: postgres:15
  #  container_name: postgres_db
  #  environment:
  #    POSTGRES_DB: ${DB_NAME}
  #    POSTGRES_USER: ${DB_USER}
  #    POSTGRES_PASSWORD: ${DB_PASSWORD}
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"

volumes:
  postgres_data: