"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gs8(0p)qfci75s8r-uvj&bi100##am5)uk9@26yq*zjimo2=sl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0''13.201.62.154']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # For token blacklisting on logout
    'corsheaders',  # CORS support for frontend
    'frontend',
    # 'channels',  # Commented out - install with: pip install channels
]
ASGI_APPLICATION = "backend.asgi.application"



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
          'ENGINE': 'django.db.backends.postgresql', 
        'NAME': 'rudraride_db', 
        'USER': 'app_user', 
        'PASSWORD': 'ept@123', 
        'HOST': '15.207.8.95',   # PgBouncer 
        'PORT': '6432',        # PgBouncer port 
        'CONN_MAX_AGE': 0,     # 🔑 REQUIRED with PgBouncer
 
    }
}
 


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://13.201.62.154:3000",
    "http://13.201.62.154:3001",
]

# Allow credentials (cookies, authorization headers) to be included in requests
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# AUTH_USER_MODEL is not set - using default Django User model
# RidesUser is a regular model connected to existing rides_user table, not a User model

# Django REST Framework Configuration
# For development (DEBUG=True): Allow unauthenticated access for easier testing
# For production (DEBUG=False): Require authentication
if DEBUG:
    DEFAULT_PERMISSION = 'rest_framework.permissions.AllowAny'
else:
    DEFAULT_PERMISSION = 'rest_framework.permissions.IsAuthenticated'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'frontend.authentication.FrontendUserJWTAuthentication',  # Custom JWT auth for FrontendUser
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback to default
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        DEFAULT_PERMISSION,
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    # Extended token lifetimes for admin users - tokens expire after 30 days (720 hours)
    # This prevents admin users from being logged out after 10 minutes
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # Access token valid for 30 days (prevents 10-minute logout)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Refresh token valid for 30 days
    'ROTATE_REFRESH_TOKENS': True,  # Rotate refresh token on each use
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Email Configuration - Real-time Email Delivery
# IMPORTANT: Choose ONE of the following options:

# OPTION 1: Console Backend (for testing - emails print to console)
# Use this for development/testing - no email configuration needed
# Emails will be printed to the terminal/console instead of being sent
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# OPTION 2: SMTP Backend (for real email delivery) - CURRENTLY ACTIVE
# Configure your email settings below for real email delivery
# For Gmail, you MUST use an App Password (not your regular password)
# Get App Password from: https://myaccount.google.com/apppasswords
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change to your SMTP server (e.g., 'smtp.gmail.com', 'smtp-mail.outlook.com', 'smtp.mail.yahoo.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# ⚠️ REQUIRED: Fill in your email credentials
# Credentials are loaded from environment variables (recommended) or .env file
# python-dotenv is installed and will automatically load .env file from backend/ directory
#
# RECOMMENDED: Create a .env file in the backend/ directory with:
#   EMAIL_HOST_USER=your-email@gmail.com
#   EMAIL_HOST_PASSWORD=your-16-char-app-password
#
# Or set as system environment variables
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'gurypavithra41@gmail.com')  # Your Gmail address
# ⚠️ CRITICAL: Gmail App Password must be exactly 16 characters (no spaces)
# Get a new app password from: https://myaccount.google.com/apppasswords
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'mjdbwjgohrrtxfqh')  # ⚠️ REQUIRED: Add your Gmail App Password here (exactly 16 characters, no spaces)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@rudraadmin.com'  # Default sender email

# Gmail Configuration Instructions:
# 1. Enable 2-Step Verification on your Google account (required for app passwords)
# 2. Go to: https://myaccount.google.com/apppasswords
# 3. Select "Mail" and your device, then click "Generate"
# 4. Copy the 16-character password (it will look like: abcd efgh ijkl mnop)
# 5. Remove ALL spaces - the password should be exactly 16 characters with no spaces
# 6. Paste it in EMAIL_HOST_PASSWORD above (or set as environment variable)
#
# Common Issues:
# - Error 535 "Username and Password not accepted": App password is incorrect/expired
# - Password has spaces: Remove all spaces (Gmail app passwords are 16 chars, no spaces)
# - Password too long/short: Must be exactly 16 characters
# - 2-Step Verification not enabled: Enable it first, then create app password

# Other Email Providers:
# - Outlook/Hotmail: EMAIL_HOST = 'smtp-mail.outlook.com', EMAIL_PORT = 587
# - Yahoo: EMAIL_HOST = 'smtp.mail.yahoo.com', EMAIL_PORT = 587
# - Custom SMTP: Update EMAIL_HOST and EMAIL_PORT accordingly

# ⚠️ IMPORTANT: Fill in EMAIL_HOST_USER and EMAIL_HOST_PASSWORD above to enable real email delivery
# If these are empty, emails will fail to send. For testing, switch back to console backend.
